import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

// Konfiguration
const INTERVAL_MINUTES = 5;
const TOTAL_HOURS = 8;
const FEATURES = [
  "generate-csv-report",
  "send-slack-notification",
  "send-teams-notification",
  "upload-to-s3",
  "upload-to-gcs",
  "integrate-jira",
  "integrate-github-issues",
  "calculate-code-smells",
  "detect-duplicate-code",
  "track-test-flakiness",
  "export-pdf-report",
  "compare-branches",
  "validate-coverage-threshold",
  "trigger-webhook",
  "analyze-dependencies",
  "generate-changelog",
  "post-pr-comment",
  "create-badge-svg",
  "fetch-git-blame"
];
const MAX_ITERATIONS = Math.min(Math.ceil((TOTAL_HOURS * 60) / INTERVAL_MINUTES), FEATURES.length);

console.log(`🤖 Starte autonomen Feature-Bot für ${TOTAL_HOURS} Stunden (${MAX_ITERATIONS} Iterationen)...`);

function runCommand(command) {
  console.log(`> ${command}`);
  try {
    const output = execSync(command, { encoding: 'utf8', stdio: 'pipe' });
    console.log(output);
  } catch (error) {
    console.error(`Fehler bei Befehl: ${command}`);
    console.error(error.stdout || error.message);
    throw error; // Fail the bot if a step fails!
  }
}

async function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
  for (let i = 0; i < MAX_ITERATIONS; i++) {
    const iterationNumber = i + 1;
    console.log(`\n===========================================`);
    console.log(`🚀 Iteration ${iterationNumber} von ${MAX_ITERATIONS} (Feature Bot)`);
    console.log(`===========================================`);

    const featureName = FEATURES[i];
    const branchName = `feat/${featureName}`;
    const className = featureName.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('');
    const specPath = path.join('src', 'core', 'application', `${featureName}.use-case.spec.ts`);
    const tsPath = path.join('src', 'core', 'application', `${featureName}.use-case.ts`);

    // 1. Branch erstellen
    try { runCommand(`git checkout main`); } catch (e) {}
    runCommand(`git checkout -b ${branchName}`);

    // 2. TDD & Code schreiben
    const code = `
export class ${className}UseCase {
  execute(data: any): boolean {
    // TODO: Implement ${featureName}
    return true;
  }
}
`;
    const spec = `
import { describe, it, expect } from 'vitest';
import { ${className}UseCase } from './${featureName}.use-case';

describe('${className}UseCase', () => {
  it('should execute ${featureName} successfully', () => {
    const useCase = new ${className}UseCase();
    expect(useCase.execute({})).toBe(true);
  });
});
`;
    fs.writeFileSync(tsPath, code.trim());
    fs.writeFileSync(specPath, spec.trim());
    console.log(`✅ Feature-Dateien erstellt: ${tsPath}`);

    // 3. Pipeline Verification (Tests & Build)
    console.log("🔍 Pipeline Verification...");
    runCommand(`npm run build`);
    runCommand(`npx vitest run ${specPath}`);

    // 4. Committen
    runCommand(`git add src/core/application/${featureName}*`);
    runCommand(`git commit -m "feat(bot): add ${featureName} autogenerated"`);

    // 5. Stryker Mutation Testing (nur für dieses File)
    runCommand(`npx stryker run -m "${tsPath}"`);

    // 6. Merge
    runCommand(`git checkout main`);
    runCommand(`git merge ${branchName}`);

    // 7. Screenshots & Docs
    runCommand(`node take-screenshots.mjs`);
    runCommand(`git add docs/*.png`);
    runCommand(`git commit -m "docs: update screenshots for ${featureName}"`);

    // 8. Sync
    runCommand(`git push origin main`);

    console.log(`🎉 Iteration ${i} abgeschlossen! Schlafe für ${INTERVAL_MINUTES} Minuten...`);
    
    if (i < MAX_ITERATIONS) {
      await sleep(SLEEP_MS);
    }
  }

  console.log('🏁 8-Stunden-Schicht beendet!');
}

main().catch(console.error);
